### ISSUE TITLE
Min For Valid Parenthesis

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#1]
`Problem:` _minimum add to make a valid parenthesis_

- Given a string of parentheses, find the minimum number of parentheses that need to be added to make the string valid.

- The function should take a single string as input. This string will consist entirely of parentheses characters ('(' and ')'). The string may be empty or contain any valid or invalid combination of parentheses.

1. Follow and Read the Contributing Guidelines.

2. Only the assigned person is allowed to raise the PR on this Issue.

3. To get this issue assigned to you comment on this issue, along with your name, branch and year.

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by snehautekar05** [comment]
Heyy @Saket6198 ,can you assign this issue to me?

**Comment by Saket6198** [comment]
@snehautekar05 please read the rules properly and comment with your name, branch, year and college name.

**Comment by snehautekar05** [comment]
@Saket6198
 Name-Sneha Utekar
Branch-IT
Year-4th 
College Name-VESIT
