### ISSUE TITLE
Rotate array by K-steps

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#11]
`Problem:` You are given an array of integers nums. Your task is to rotate the array to the right by k positions, where k is a non-negative integer.

The input should consist of an integer array nums[] representing the array elements, and a non-negative integer k representing the number of positions by which the array should be rotated to the right.

---

1. Follow and Read the Contributing Guidelines.

2. Only the assigned person is allowed to raise the PR on this Issue.

3. To get this issue assigned to you comment on this issue, along with your name, branch, year and college name.

`Note: `Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by sujalcharati** [comment]
hey can i be assigned?
 Name: sujal kumar charati
Branch: **CSE**
Year: 2nd
College: Parala maharaja engineering college

**Comment by Kriagr23** [comment]
Please assign this issue to me under hacktoberfest
Name : Krishna Agrawal
Branch: IT
year : TY
College : PCE
