### ISSUE TITLE
String Cmp after Deletion Using Stack

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#14]
`Problem:` You are provided with two strings s and t. Your task is to determine if they are identical when typed into empty text editors, where the character '#' acts as a backspace operation.

Note: If backspacing occurs when there is no character to delete, the text remains empty.

Return true if both strings are equal after all deletion operation else false ([Question](https://github.com/gdgpce/DSA-Challenges-2024/blob/main/Stack/Deletion-String-Compare/deletion_stringcmp.txt))

---

1. Follow and Read the [Contributing Guidelines.](https://github.com/gdgpce/DSA-Challenges-2024/blob/main/CONTRIBUTING.md)

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch, year and college name_**.

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by negativenagesh** [comment]
@Saket6198 

### assign this issue to me

Name: Subrahmanya Gaonkar
Branch: Computer Science - Data Science
Year - (B. Tech) 3rd year 5th sem
College: Vidyashilp University

**Comment by Saket6198** [comment]
@negativenagesh alright, make sure to write your code with proper working of it :)

**Comment by negativenagesh** [comment]
> @negativenagesh alright, make sure to write your code with proper working of it :)

Absolutely
