### ISSUE TITLE
Next Greater Element

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#19]
`Problem:` You're given an array `nums` of non-negative integers, indexed starting from 0. For each element in the array, you need to determine its second greater integer. Here's the condition for the second greater integer:

For each element `nums[i]`, find a `nums[j]` such that:

- ` j > i`

- `nums[j] > nums[i]`

- There is exactly one intermediate index `k` such that `nums[k] > nums[i]` and `i < k < j.`

If no such `nums[j]` exists, the second greater integer is considered -1.

For example, in the array `[1, 2, 4, 3],` the second greater integer for:

`1` is `4`
`2` is `3`
`3` and `4` do not have any second greater integer, so they return `-1.`

Return a vector `answer` where `answer[i]` represents the second greater integer of` nums[i].`

---

1. Follow and Read the Contributing Guidelines.

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch, year and college name._**

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by joaotomy** [comment]
hey! can you please assign this issue to me?
name: João
Branch: sth
Year: 3rd
College: Universidade de Coimbra

**Comment by Ruchika2005** [comment]
Name: Ruchika Patil
Branch: Computer Engineering
Year: SY
College: CCOEW
Could you please assign this issue to me ?

**Comment by Saket6198** [comment]
@joaotomy sure, go ahead :)
