### ISSUE TITLE
Search-String-Pattern

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#2]
`Problem:` Given a text string and a pattern string, find all occurrences of the pattern within the text and return their starting indices. The task is to print the indexes of all the occurrences of pattern string in the text string in a vector (For additonal info refer the [[folder](https://github.com/gdgpce/DSA-Challenges-2024/blob/main/Strings/Search-Pattern/pattern_string.txt)]

- The function should take two strings as input:

  1. Text string: This is the string where you want to search for occurrences of the pattern.
  2. Pattern string: This is the string you are searching for within the text string.
  
  
---

1. Follow and Read the Contributing Guidelines.

2. Only the assigned person is allowed to raise the PR on this Issue.

4. To get this issue assigned to you comment on this issue, along with your name, branch and year.

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by VaradJadhav** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name: Varad Jadhav
Branch: CS
year: 4th
I can solve this problem in C++ in linear time and space

**Comment by avani-srivastavaa** [comment]
Please assign me this issue
Name: Avani Srivastava
Branch: CS
year: 2nd

I can solve this problem in linear time in C++ in-place!

**Comment by avani-srivastavaa** [comment]
Hey @gdscpce please assign me this issue
Name: Varad Jadhav
Branch: CS
year: 4th

**Comment by avani-srivastavaa** [comment]
Please assign me this issue
Name: Avani Srivastava
Branch: CS
Year: 2nd

**Comment by avani-srivastavaa** [comment]
Please assign me this issue
Name: Avani Srivastava
Branch: CS
Year: 2nd
College: PCE Panvel

**Comment by shridharkhare** [comment]
Please assign this issue to me.

Name: Shridhar Ganesh Khare
Branch: Computer Engineering
Year: Sophomore 
College: Pillai College Of Engineering, New Panvel

**Comment by roshankraveendrababu** [comment]
please assign this issue to me!!!.
name: K.R.Roshan
Branch: Computer Science
year: 3rd year
College: sathyabama institute of science and technology, Chennai

i can solve this problem is the least time and space complexity in python
