### ISSUE TITLE
Remove all occurences in a Linked List

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#20]
`Problem:` You're given the head of a linked list and a specific integer value val. The task is to remove every node in the linked list that contains the value` val `and return the updated list's head.

_**Example 1:**_

**Input:**
head = [1, 2, 6, 3, 4, 5, 6], val = 6

**Explanation:**
All nodes with the value 6 are removed, so the final linked list is [1, 2, 3, 4, 5].

You will receive a linked list represented by its head node and an integer value val to remove from the list. The Structure of the Linked list is : 

```
class Node{
public:
    int val;
    Node* next;

    Node(int s){
        val = s;
        next = NULL;
    }
};
```
Return the head of the modified linked list, where all nodes with the value val have been removed. If the list becomes empty, return an empty list.

---

1. Follow and Read the Contributing Guidelines.

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch, year and college name._**

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by gargiisc** [comment]
@gdscpce @Saket6198 
Please assign this issue to me!!
Name: Gargi C
Branch: Computer Engineering
Year: TY
College: UMIT

**Comment by Ruchika2005** [comment]
Name: Ruchika Patil
Branch: Computer Engineering
Year: SY
College: CCOEW
Could you please assign this issue to me ?
