### ISSUE TITLE
Replace With Rank

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#5]
`Problem:` You are given an vector of integers called order. Your task is to transform each element by assigning it a rank based on its value.

The ranking system works as follows:

- Ranks start at 1 and increase incrementally.

- Higher values in the array receive higher ranks.

- If two or more elements have the same value, they are assigned the same rank.

- Ensure that the ranks are assigned in the smallest possible way.

 _**The function accepts a vector of integers, return that vector with rank replaced with its order**_

---

1. Follow and Read the Contributing Guidelines.

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch and year_**.

`Note: `Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by VaradJadhav** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name: Varad Jadhav
Branch: CS
Year: 4th

**Comment by roshankraveendrababu** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name: K.R.Roshan
Branch: CS
College: Sathyabama institute of science and technology
Year: 3rd

**Comment by Saket6198** [comment]
@roshankraveendrababu sure, go ahead :)
