### ISSUE TITLE
Height of Binary Tree

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#6]
`Problem:` You are provided with the root of a binary tree. The task is to find its maximum depth, defined as the count of nodes along the longest route from the root to the deepest leaf node.
<p align = "center">
<img src="https://github.com/user-attachments/assets/c34171a1-67d7-460c-8558-a7cec6921f80">
</p>

The input will be the root node of a binary tree, represented by an predefined instance of a Tree class. Each node in the tree contains a value, a left child, and a right child, with the tree structure already initialized. **The function will return the maximum depth of the tree in integer:**
```
class Tree{
public:
    int val;
    Tree* left;
    Tree* right;

    Tree(int s){
        val = s;
        left = right = NULL;
    }
};
```
---

1. Follow and Read the [Contributing Guidelines.](https://github.com/gdgpce/DSA-Challenges-2024/blob/main/CONTRIBUTING.md)

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch and year._**

4. Note: Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by VaradJadhav** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name : Varad Jadhav
Branch: CS
year: 4th

**Comment by roshankraveendrababu** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name : K.R.Roshan
Branch: CS
college: sathyabama institute of science and technology
year: 3rd

**Comment by Grahish-code** [comment]
Hey @Saket6198 @gdscpce please assign me this issue
Name : Grahish
Branch: CS
college: pillai college of engineering
year: 3rd
