### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by Saket6198** [gdgpce/DSA-Challenges-2024#9]
`Problem:` Given an integer array and another integer element. The task is to find if the given element is present in array or not.

The input consists of an integer n representing the size of the array, followed by an integer array arr[] of length n, and an integer x to be searched within the array.
 
If the element is present then return true, otherwise false.

---

1. Follow and Read the Contributing Guidelines.

2. Only the **_assigned person is allowed_** to raise the PR on this Issue.

3. To get this issue assigned to you **_comment on this issue, along with your name, branch, year and college name._**

`Note:` Make sure to put the question under the relevant folder structure, and then make another folder having the question name and inside that folder you can write your solution in any preferred language.

**Comment by Kriagr23** [comment]
Please assign this issue to me under hacktoberfest
Name : krishna agrawal
Class : TY IT 
College Name : Pce
